// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe3iXLkrDVrVyWEVsQUQLVghLxIeJ5NSk',
    appId: '1:42249373538:web:36d304eaede4695f69ce3b',
    messagingSenderId: '42249373538',
    projectId: 'smartchickapp',
    authDomain: 'smartchickapp.firebaseapp.com',
    storageBucket: 'smartchickapp.firebasestorage.app',
    measurementId: 'G-F7M4QRBQ60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0B_EzuMhVcr0Bt6L5KpIIdhxJHck3r6k',
    appId: '1:42249373538:android:bfb23350a4ffd36a69ce3b',
    messagingSenderId: '42249373538',
    projectId: 'smartchickapp',
    storageBucket: 'smartchickapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyvbHytGo6XzrDfJkGs2JUvRmG01fBRKY',
    appId: '1:42249373538:ios:f47301b87feaa2a869ce3b',
    messagingSenderId: '42249373538',
    projectId: 'smartchickapp',
    storageBucket: 'smartchickapp.firebasestorage.app',
    iosBundleId: 'com.example.smartChick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyvbHytGo6XzrDfJkGs2JUvRmG01fBRKY',
    appId: '1:42249373538:ios:f47301b87feaa2a869ce3b',
    messagingSenderId: '42249373538',
    projectId: 'smartchickapp',
    storageBucket: 'smartchickapp.firebasestorage.app',
    iosBundleId: 'com.example.smartChick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe3iXLkrDVrVyWEVsQUQLVghLxIeJ5NSk',
    appId: '1:42249373538:web:60c138f858b3aef369ce3b',
    messagingSenderId: '42249373538',
    projectId: 'smartchickapp',
    authDomain: 'smartchickapp.firebaseapp.com',
    storageBucket: 'smartchickapp.firebasestorage.app',
    measurementId: 'G-QCLYHV11ZM',
  );
}
